version: "3.9"
services:
  hermes:
    build:
      context: .
      dockerfile: hermes.Dockerfile
      args:
        TAG: v0.11.1
    image: hermes:0.11.1
    volumes:
      - "hermes-home:/home/hermes"
      - ".:/config:ro"
    command:
      - -c
      - /config/hermes.config
      - start
volumes:
  hermes-home:
    external: true
