version: "3.9"
services:
  hermes:
    build:
      context: .
      dockerfile: hermes.Dockerfile
      args:
        TAG: df0cc5d312a7467cc0252ce16391a17b3b57c714
    image: hermes:0.12.0-pre
    volumes:
      - "hermes-home:/home/hermes"
      - ".:/config:ro"
    command:
      - -c
      - /config/hermes.config
      - start
volumes:
  hermes-home:
    external: true
